<?php

namespace AppBundle\Repository;

/**
 * TodoListRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TodoListRepository extends \Doctrine\ORM\EntityRepository
{
}
